### ISSUE TITLE
Result of your code and output of openssl are not the same with sha256

### ISSUE THREAD

**Issue by dalmatele** [Egor-Skriptunoff/pure_lua_SHA2#1]
For string "test"
your lib output is: 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
openssl output is: f2ca1bb6c7e907d06dafe4687e579fce76b37e4e93b7605022da52e6ccc26fd2

**Comment by Egor-Skriptunoff** [comment]
@dalmatele 
Both my lib and openssl are correct:
```
Lua 5.4.0  Copyright (C) 1994-2019 Lua.org, PUC-Rio
> sha = require'sha2'
> sha.sha256"test"
9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
> sha.sha256"test\n"
f2ca1bb6c7e907d06dafe4687e579fce76b37e4e93b7605022da52e6ccc26fd2

```
The difference is due to terminating EOL
