### ISSUE TITLE
Error when used with OpenWrt lua 5.1

### ISSUE THREAD

**Issue by lePereT** [Egor-Skriptunoff/pure_lua_SHA2#2]
Hi, I think that your code isn't accurately detecting Lua 5.1.5 on OpenWrt. Using a simple `sha.sha256("test")` generates the following error:
```
lua: ./sha2.lua:309: bad argument #2 to 'string_format' (integer expected, got number)
stack traceback:
        [C]: in function 'string_format'
        ./sha2.lua:309: in function 'HEX'
        ./sha2.lua:2467: in function <./sha2.lua:2433>
        (tail call): ?
        (tail call): ?
        shatest.lua:12: in function 'test'
        shatest.lua:16: in main chunk
        [C]: ?
```
Is there anything I can do to help debug?

**Comment by Egor-Skriptunoff** [comment]
Thanks for bugreport.

It seems OpenWrt has added integer datatype to Lua 5.1 and prohibited `%d` and `%x` for doubles:  
https://github.com/openwrt/openwrt/blob/master/package/utils/lua/patches/010-lua-5.1.3-lnum-full-260308.patch#L2450-L2455  

1) Can you run `x=42.0; print(string.format("%08x", x))` on your system?  
2) Can you run `x=42.0; print(string.format("%08x", x % 4294967296))`?  
3) Is rewriting the line 309 of `sha2.lua` as follows solves the problem?
```lua
      return string_format("%08x", math.floor(x % 2^32))
```
4) Is rewriting the line 309 of `sha2.lua` as follows solves the problem?
```lua
      return string_format("%08x", (x + 2^31) % 2^32 - 2^31)
``` 
5) Is rewriting the line 309 of `sha2.lua` as follows solves the problem?
```lua
      return string_format("%08x", math.floor((x + 2^31) % 2^32 - 2^31))
```

**Comment by lePereT** [comment]
> 1. Can you run `x=42.0; print(string.format("%08x", x))` on your system?

0000002a
> 2. Can you run `x=42.0; print(string.format("%08x", x % 4294967296))`?

0000002a
> 3. Is rewriting the line 309 of `sha2.lua` as follows solves the problem?
> 
> ```lua
>       return string_format("%08x", math.floor(x % 2^32))
> ```
Nope, still get:
```
./sha2.lua:309: bad argument #2 to 'string_format' (integer expected, got number)
stack traceback:
	[C]: in function 'string_format'
	./sha2.lua:309: in function 'HEX'
	./sha2.lua:2470: in function <./sha2.lua:2436>
	(tail call): ?
	(tail call): ?
	stdin:1: in main chunk
	[C]: ?
```
> 
> 4. Is rewriting the line 309 of `sha2.lua` as follows solves the problem?
> 
> ```lua
>       return string_format("%08x", (x + 2^31) % 2^32 - 2^31)
> ```
Yes!
```
> print(sha.sha256("your string"))
d14d691dac70eada14d9f23ef80091bca1c75cf77cf1cd5cf2d04180ca0d9911
```
> 5. Is rewriting the line 309 of `sha2.lua` as follows solves the problem?
> 
> ```lua
>       return string_format("%08x", math.floor((x + 2^31) % 2^32 - 2^31))
> ```
Yes x 2!
```
> print(sha.sha256("your string"))
d14d691dac70eada14d9f23ef80091bca1c75cf77cf1cd5cf2d04180ca0d9911
```
> It seems OpenWrt has added integer datatype to Lua 5.1 and prohibited `%d` and `%x` for doubles:
> https://github.com/openwrt/openwrt/blob/master/package/utils/lua/patches/010-lua-5.1.3-lnum-full-260308.patch#L2450-L2455

I'm quite new to Lua and OpenWrt. Are there any consequences to OWT's changes, in terms of compatibility, performance and any other unusual bugs, that you can think of to watch out for?

**Comment by Egor-Skriptunoff** [comment]
Fixed.

> Are there any consequences to OWT's changes, in terms of compatibility

In Lua 5.1 `string.format("%x", 2^31)` gives correct result.  
But OpenWrt's Lua now partially implements behavior of Lua 5.3 (built with unusual numeric configuration `double + int32`), where `string.format("%x", 2^31)` fails.
