### ISSUE TITLE
Incorrect values returned from bin2base64

### ISSUE THREAD

**Issue by treahard** [Egor-Skriptunoff/pure_lua_SHA2#3]
First - thank you for your excellent work!.

I attach a short script showing a problem with bin2base64.  The script generates a random 10 character string and attempts to convert it via base64 using sha.bin2base64 and compares it with another base64 algorithm.  Mismatches are outputted.

I hope this helps you discover the bug in bin2base64.

Regards,

Tom

local sha = require 'sha2'

-- character table string
local b='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'

-- encoding
function encode_b64(data)
    return ((data:gsub('.', function(x) 
        local r,b='',x:byte()
        for i=8,1,-1 do r=r..(b%2^i-b%2^(i-1)>0 and '1' or '0') end
        return r;
    end)..'0000'):gsub('%d%d%d?%d?%d?%d?', function(x)
        if (#x < 6) then return '' end
        local c=0
        for i=1,6 do c=c+(x:sub(i,i)=='1' and 2^(6-i) or 0) end
        return b:sub(c+1,c+1)
    end)..({ '', '==', '=' })[#data%3+1])
end

local charset = {}
for i = 0,  255 do table.insert(charset, string.char(i)) end
math.randomseed(os.time())

function string.random(length)

  if length > 0 then
    return string.random(length - 1) .. charset[math.random(1, #charset)]
  else
    return ''
  end
end

for i=1,100 do
  local s = string.random(10)
  if encode_b64(s) ~= sha.bin2base64(sha.hex2bin(s)) then
    print('error',encode_b64(s),sha.bin2base64(sha.hex2bin(s)))
  end
end

**Comment by Egor-Skriptunoff** [comment]
```
if encode_b64(s) ~= sha.bin2base64(sha.hex2bin(s)) then
```
Your string `s` is already binary, so why do you apply `hex2bin`?  
You should write the following instead:  
```
if encode_b64(s) ~= sha.bin2base64(s) then
```

**Comment by treahard** [comment]
Thank you for looking at this.  Silly mistake.

Regards
