### ISSUE TITLE
bin2hex add, please.

### ISSUE THREAD

**Issue by z0hm** [Egor-Skriptunoff/pure_lua_SHA2#4]
something like this (for luajit 2.1):
        local ffi=require 'ffi'
        local C,ibuf,obuf = ffi.C,ffi.new("unsigned char[?]",buf_size),ffi.new("unsigned char[?]",buf_size*2)
        while true do
          local n = tonumber(C.fread(ibuf,1,ffi.sizeof(ibuf),f_in))
          if n==0 then break end
          for i=0,n-1 do
            local low  = ibuf[i]%16
            local high = bit.rshift(ibuf[i],4)
            obuf[i+i]   = high<10 and high+48 or high+55
            obuf[i+i+1] = low<10  and low+48  or low+55
          end
          C.fwrite(obuf,1,n+n,f_out)
        end

Thanks for very good (fast!) checksum library

**Comment by z0hm** [comment]
Only for string message, like other functions.

**Comment by z0hm** [comment]
function bin2hex(binary_string)
      local result = {}
      for pos = 1, #binary_string do
         local n = byte(sub(binary_string, pos, pos))
         local low  = n % 16
         local high = (n - low) / 16
         high = high<10 and high+48 or high+55
         low  = low<10  and low+48  or low+55
         result[#result + 1] = char(high)..char(low)
      end
      return table_concat(result)
   end

**Comment by Egor-Skriptunoff** [comment]
`bin2hex` has been added in the latest version.
