### ISSUE TITLE
Add url to header script

### ISSUE THREAD

**Issue by z0hm** [Egor-Skriptunoff/pure_lua_SHA2#5]
Example:
-- VERSION: 12 (2022-02-23)
-- AUTHOR:  Egor Skriptunoff
-- LICENSE: MIT (the same license as Lua itself)
-- URL: https://github.com/Egor-Skriptunoff/pure_lua_SHA

**Comment by Egor-Skriptunoff** [comment]
Thanks for the hint.
Indeed the URL may be useful if someone wants to download the latest version.
