### ISSUE TITLE
Add MIME and other popular formats 

### ISSUE THREAD

**Issue by z0hm** [Egor-Skriptunoff/pure_lua_SHA2#6]
Possible add mime encoding-decoding + other popular formats for your choice? So add mime &  base64 to tags project. Your script like me - very fast, good job.

**Comment by Egor-Skriptunoff** [comment]
@z0hm - Have you seen hash sums in quoted-printable encoding somewhere?

**Comment by z0hm** [comment]
I think I've seen it somewhere, but I can't say for sure. This function for utilities section, like hex2bin, base642bin, will help in working with message in html, email.

**Comment by Egor-Skriptunoff** [comment]
This library is for calculating hash sums.
This library is not for encoding/decoding html and email; other libraries should be used for this task.
The hexadecimal and base64 encodings are implemented here only because they are used for hash sums very frequently.

**Comment by z0hm** [comment]
This is true, but your code is so good and fast that it is tempting to use calling its functions in self scripts, so I suggest you become s little more versatile )
